public class MyDummyClass{
    public String hello='I am a teststring';

    public void testMethod(){
                 Integer a=5;
  if(a>=14){
            System.debug('This is a debug meessage');
        }
// Comment are ignored a+b=c. still indent though!
List<B>b=new List<B>{new B(),new B()};
        Integer manySpaces=  a*  3;
    
    B b2= new B(
        Name='myName'  ,
Age=14
  )
    

    }




        }