public class MyDummyClass{
    public String hello='I am a teststring';

    public void testMethod(){
                 Integer a=5;
  if(a>=14){
            System.debug('This is a debug meessage');
        }

// Comment are ignored a+b=c. still indent though!

List<B>b=new List<B>{new B(),new B()};
List<B.C>b=new List<B.C>{new B.C(),new B.C()};
List < Messaging.Emailfileattachment > myList;
            List<A>a=new List<A>  ();
        Integer manySpaces=  a*  3;
    Map<A,B>myMap=new Map<A,B>();
    B b2= new B(
        Name='myName'  ,
Age=14
  )
    
    for(int i=0;i<5;i++){
    for(Type type:types){
if(a!=b){}
string s='a+b=c';

List<A__c>myVar;
Set<A__c>mySet;
}
    }

    }

new B(
Name='asdf',
      Age=12
);



        }